// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/jenny/Documents/project/app/hooks/node_modules/.pnpm/dumi@2.2.17_@babel+core@7.23.7_@types+node@20.11.5_eslint@8.56.0_prettier@2.8.8_react-dom@18._b7ap5gv2qxpz3ubwdzytbsujei/node_modules/dumi/theme-default/slots/Hero/index.js';
